name: Publish to NuGet

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Increment latest version tag
        run: |
          git fetch --tags
          $tags = git tag --sort=-v:refname | Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' }
          $latestTag = $tags -split '\n' | Select-Object -First 1
          $versionNumbers = $latestTag -split '\.'
          $versionNumbers[-1] = [string]([int]$versionNumbers[-1] + 1)
          $newVersion = $versionNumbers -join '.'
          Write-Output "New incremented version is $newVersion"
          echo "NEXT_VERSION=$newVersion" | Out-File -Append -FilePath $Env:GITHUB_ENV
          git tag $newVersion
          git push origin $newVersion
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore RDNET/RDNET.csproj

      - name: Build
        run: dotnet build RDNET/RDNET.csproj -c Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack RDNET/RDNET.csproj -c Release --no-build -p:Version=$env:NEXT_VERSION

      - name: Push to NuGet
        run: dotnet nuget push RDNET/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
